//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Intentor.Utilities")]
[assembly: AssemblyDescription("Intentor Utilities Library.")]
[assembly: AssemblyCompany("Intentor")]
[assembly: AssemblyProduct("Intentor.Utilities")]
[assembly: AssemblyCopyright("Copyright © 2009-2012 André Intentor Martins")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("1c92bdc2-e125-49d2-ac49-811bc1b4e9f8")]
[assembly: AssemblyVersion("12.10.2.1750")]
[assembly: AssemblyFileVersion("12.10.2.1750")]


